export enum BugwardenLogParameterType {
  IP = "ip",
  TIMESTAMP = "timestamp",
  METHOD = "method",
  ORIGINAL_URL = "original-url",
  HTTP_VERSION = "http-version",
  STATUS_CODE = "status-code",
  CONTENT_LENGTH = "content-length",
  REFERRER = "referer",
  USER_AGENT = "user-agent",
  RESPONSE_TIME = "response-time",
  REQUEST_ID = "request-id",
  RESPONSE_BODY = "response-body",
  ERROR_MESSAGE = "error-message",
  ERROR_STACK = "error-stack",
  OCCURRENCE_COUNT = "occurrence-count",
}
